### ISSUE TITLE
Create a static assets cdn 

### ISSUE THREAD

**Issue by jimmoffet** [GSA/notifications-utils#2]
[We should be nice to wikipedia and create a cdn for static assets before we start hitting that us flag icon more than a few times per day](https://github.com/GSA/notifications-utils/pull/1#issue-1363935119)

**Comment by rahearn** [comment]
The cloud.gov [domain-with-cdn](https://cloud.gov/docs/services/external-domain-service/) service is almost certainly what we want to use for CDN

**Comment by stvnrlly** [comment]
And we're now using that service 👍
