### ISSUE TITLE
Enable FIPS mode for python/cryptography

### ISSUE THREAD

**Issue by rahearn** [GSA/notifications-utils#27]
Version of OpenSSL bundled with the cryptography wheel does not support FIPS-only mode

**Comment by rahearn** [comment]
OpenSSL 3 is fips validated. https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4282

There are examples of how the cryptography library itself [enables fips mode for their own CI](https://github.com/pyca/cryptography/blob/1b318af4726d75bb8d65a834c9f7325850f6320f/.github/workflows/ci.yml#L36), but each of them require re-building openssl rather than using the wheel.

**Comment by ccostino** [comment]
🤔 I wonder if some of the instructions here for `boto3` and [enforcing TLS 1.2 (or TLS 1.3)](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/security.html#enforcing-tls-1-2) may also help us in getting this taken care of ourselves - note that it also involves compiling Python using a specific version of OpenSSL.

**Comment by ccostino** [comment]
We're going to do a few things here:

- Do some more research into what it will take to build Python with FIPS-enabled OpenSSL, based on the example in `cryptography`'s own CI/CD pipeline
- Try and get a new job going in our deployment actions that will do this and produce a standalone artifact that we can use
- Reach out to cloud.gov support to talk through this requirement and our needs to see if they have any additional insights or recommendations; this is ultimately a customer responsibility as it is an app dependency we're dealing with so it's on us, but they may be able to shed some additional light

**Comment by terrazoon** [comment]
Documentation:

https://www.openssl.org/docs/manmaster/man7/fips_module.html

**Comment by ccostino** [comment]
We're waiting on guidance and follow-up from our ISSO/ISSM after we sent them details of everything we've done and researched so far.

**Comment by ccostino** [comment]
We've received guidance on this and at this point, we have to wait for cloud.gov to enable FIPS support.  Once that's in place, we can circle back with our ISSO for the next steps we can take.
